title: "Trust me, Bro": A Reddit Rhetoric Study
description: by Cicero’s analysts: Nina Geyer, Estelle Klevenz, Liane Strauch
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-slate
